### ISSUE TITLE
Exploring dataset 2 (WS Basislijst Projecten.xlsm)

### ISSUE THREAD

**Issue by kcpveen** [GoldMercy/B.A.U.-Consultants#10]

**Comment by LeCanard272** [comment]
eerst duidelijk krijgen wat er onder exploring data valt.
later kan opnieuw t shirt sizing toegepast worden

**Comment by roel0064** [comment]
Deze issue is gesplitst in:
- Puur data exploration (Dit issue)
- Prep interview verheldering dataset [https://github.com/GoldMercy/B.A.U.-Consultants/issues/32](url)
- Interview verheldering dataset [https://github.com/GoldMercy/B.A.U.-Consultants/issues/33](url)

**Comment by roel0064** [comment]
Dependency (interview) Toegevoegd

**Comment by szra0003** [comment]
Deze issue is closed. De reden is dat nadat de dependency, die aan deze issue is gekoppeld wordt uitgevoerd, deze ticket dan automatisch wordt afgerond.
