### ISSUE TITLE
Demo Sprint 3 maken

### ISSUE THREAD

**Issue by szra0003** [GoldMercy/B.A.U.-Consultants#106]
Een demo maken om te presenteren naar de opdrachtgever.

**Comment by LeCanard272** [comment]
Demo is gemaakt. Staat in HZ University of Applied Sciences\B.A.U. Consultants - General\Agile\Sprint 3
Vanmiddag na standdown deze reviewen met de rest van de club
2* 20 min = 40 min mee bezig geweest... L kan veranderen in een XS dus bij de volgende presentatie maken
