### ISSUE TITLE
Functioneel testen dashboard voorbereiden

### ISSUE THREAD

**Issue by Nienkedn** [GoldMercy/B.A.U.-Consultants#109]
Een testplan schrijven zodat alle testen een uniforme opzet hebben.

**Comment by kcpveen** [comment]
Vragen:
![image](https://user-images.githubusercontent.com/36401158/95456498-b48b9b00-096f-11eb-9e13-70d1dccd40f6.png)
Zouden jullie hier informatie willen zien, zo ja welke?

![image](https://user-images.githubusercontent.com/36401158/95456785-282da800-0970-11eb-86d8-ed5072543c24.png)
Willen jullie liever een lijst zien waarin je de individuele PI's kunt uitklappen of heb je liever de PI's onderkaar als hoe het nu staat met details per balk?

**Comment by Nienkedn** [comment]
Ik heb een document gemaakt met daarin uitleg van de mock up en vervolgens vragen die gesteld zouden kunnen worden tijdens het testen. Moet nog met @HasinaNoori en @kcpveen  overlegd worden. 
3 uur bezig geweest

**Comment by Nienkedn** [comment]
De enquete voor het testen is af en is te vinden op: https://docs.google.com/forms/d/1q5WKtjJInaBU_LJhUvYrPUe3jZvXK5SkuV4Zl-ZZRPg/prefill 
30 minuten mee bezig geweest

**Comment by HasinaNoori** [comment]
De test volledig gecheckt. 30 minuten mee bezig geweest.
