### ISSUE TITLE
Interview Fleur afnemen

### ISSUE THREAD

**Issue by roel0064** [GoldMercy/B.A.U.-Consultants#111]
Houd het interview met Fleur over data aanleveren aan naar de stuurhut

**Comment by HasinaNoori** [comment]
Interview ingepland op dinsdag13 oktober tussen 10.30 en 12.00 via teams. Interview zal worden afgenomen door Rik & Niels.

**Comment by LeCanard272** [comment]
interview is afgenomen, of informatie nuttig is moet nog overlegd worden in het team
interview was 1.5u. uitwerking volgt nog.
