### ISSUE TITLE
Interview Fleur verwerken

### ISSUE THREAD

**Issue by roel0064** [GoldMercy/B.A.U.-Consultants#112]
Verwerk de uitkomsten van het interview met Fleur.

**Comment by szra0003** [comment]
Heb het tweede gedeelte van het interview met fleur uitgewerkt.

Deze is te vinden op teams onder General/Interviews waterschap/Afgenomen interviews. De bestandsnaam is Interview Fleur part 2.docx. De tijdsbesteding van dit onderdeel is 4,5 uur. (Moet nog samengevoegd worden met deel 1 van het interview, die gemaakt wordt door Rik)
