### ISSUE TITLE
Onderzoek aanleverings-data

### ISSUE THREAD

**Issue by Nienkedn** [GoldMercy/B.A.U.-Consultants#113]
[Uitvraag voortgang prestaties SN 2019-2023 per 1 september 2020.xlsx](https://github.com/GoldMercy/B.A.U.-Consultants/files/5348128/Uitvraag.voortgang.prestaties.SN.2019-2023.per.1.september.2020.xlsx)
Om aan de slag te kunnen in Tableau moeten we onderzoeken of we de data die gebruikt wordt om de sturingsmonitor in te vullen te gebruiken is om een dashboard te maken.

**Comment by kcpveen** [comment]
Ik pak deze op.

**Comment by kcpveen** [comment]
Vandaag voor 6 uren aan deze issue gewerkt. Hierbij ook direct het besluit om de issue te vergroten tot een XL.

In het Excel bestand zelf heb ik handmatig de laatste kolom waarin informatie stond van de kolom "'Aanvullende toevoegingen, opmerkingen & bespreekpunten richting monitor september 2020 (intern)" samen gevoegd. Het zou beter zijn als deze stap in Tableau Prep gedaan werd maar aan gebrek aan kennis en tijd heb ik het nu zo gedaan.

Er is nu 1 schoonmaak stap gedaan in Tableau Prep waarin 24 veranderingen plaatsvinden. Het resultaat van deze schoonmaak stap is te zien in het CSV bestand genaamd: "Voortgang Prestatie Dataset v1.0.csv" .

DEZE ISSUE IS NOG NIET AF. De volgende schoonmaak stappen die ik nu al kan zien (Er zullen er vast nog wel meer bij komen) zijn als volgt:
- Het opsplitten van de "Doelstelling 2020" kolom. Dit met betrekking tot dubbele data in een rij bv. 20%-70%
- Samen voegen van de kolommen "Realisatie 1 mei 2020" en "Realisatie 1 sep 2020" om tot 1 kolom te komen met de resultaten.
- etc...

Ik voeg de 3 files die betreking hebben tot deze issue toe

 op teams in:
General\Dashboard\DataPrep\Voortgang Prestatie Data

De files zijn:
- "Uitvraag voortgang prestaties SN 2019-2023 per 1 september 2020.xlsx"
- "Voortgang Prestatie Dataset v1.0.csv"
- "Voortgang Prestatie DataPrep Waterschap.tfl"

**Comment by kcpveen** [comment]
Vandaag nog eens 2.5u aan gewerkt.
De doelstelling 2020 kolom is gesplit en redelijk opgeschoond maar is nog niet af.

Hierna overgeschakeld naar issue #109 met als doel het sprint doel te proberen te behalen.

**Comment by kcpveen** [comment]
De data van de kolommen realisatie (mei & sep) en doelstelling zijn opgeschoond en gesplit.
De originele kolommen hebben "Info" in hun naam en staan nog op het string formaat.
De nieuwe kolommen hebben "Data" in hun naam en staan op het decimaal formaat.

Resultaat:
"Realisatie Data 1 mei 2020" & "Realisatie Info 1 mei 2020"
"Realisatie Data 1 sep 2020" &  "Realisatie Info 1 sep 2020"

"Max - Doelstelling Data 2020"
"Min - Doelstelling Data 2020"
"Doelstelling Info 2020"

**Comment by kcpveen** [comment]
Medewerkers kolom is opgeschoond.
Er zijn nu twee outputs in de flow: één met de Info kolommen en één zonder de info kolommen in de dataset.

De nieuwe gegenereerde outputs en prep file zijn geupload naar de teams folder: 
General\Dashboard\DataPrep\Voortgang Prestatie Data

Vandaag 2.5 uren gewerkt aan deze user story.

Deze user story is nu klaar voor review.
