### ISSUE TITLE
Data e-mail Michiel doornemen

### ISSUE THREAD

**Issue by roel0064** [GoldMercy/B.A.U.-Consultants#115]
Michiel heeft ons de data doorgestuurd die beloofd was. Deze ticket is bedoeld om deze informatie te verwerken in het al bestaande document waarin het interview staat.

Edit: de data is te omvangrijk om toe te voegen aan het uitgewerkte interview. Hiervoor is een apart data understanding document nodig.

**Comment by roel0064** [comment]
Documenten doorgespitst. Ik ben tot de realisatie gekomen dat dit geen toevoeging meer kan wezen op alleen het interview.
~45min

**Comment by roel0064** [comment]
"Data e-mail Michiel verwerken" naar "Data e-mail Michiel doornemen" vranderd. Per onderdeel kan een data understanding ticket aangemaakt worden.

**Comment by roel0064** [comment]
In het uitgewerkte interview document zijn comments toegevoegd die verwijzen naar data die door Michiel doorgestuurd is.

**Comment by roel0064** [comment]
Linkjes van Michiel uit de mail toegevoegd aan het document als extra verheldering.

**Comment by roel0064** [comment]
Tijd:
~1:30 uur data doornamen / begrijpen.
~0:30 uur informatie mail en data koppelen aan uitgewerkt interview.

2 uur totaal

**Comment by LeCanard272** [comment]
data is te vinden onder interviews waterschap>uitgewerkt interview van M.Pouwer in teams

**Comment by LeCanard272** [comment]
further review by OSC en LD needed
