### ISSUE TITLE
Opzetten advies over gebruiksvriendelijkheid Tableau

### ISSUE THREAD

**Issue by Nienkedn** [GoldMercy/B.A.U.-Consultants#117]
Eerste opzet onderzoek gebruiks(vriendelijk) van Tableau, bijvoorbeeld: kan je het dashboard zonder Tableau gebruiken

**Comment by Nienkedn** [comment]
Ik ben bezig geweest met het experimenteren met een dashboard. Later ook met de dataset van Kevin bezig geweest. Mijn aantekeningen heb ik op papier dus die moet ik nog naar een document schrijven.

**Comment by roel0064** [comment]
Dit issue moet onderverdeeld worden onder kleinere issues.
