### ISSUE TITLE
Doornemen van adviesplan

### ISSUE THREAD

**Issue by szra0003** [GoldMercy/B.A.U.-Consultants#119]
We nemen het adviesrapport door en kijken wat we deze sprint kunnen invoeren als veranderplan. Hierbij kijken we de CYC portfolio's in van iedereen voor ideeën.

**Comment by roel0064** [comment]
Alle CYC portfolio's zijn doorgenomen. Hieruit is een lijst met kopjes gekomen met mogelijke onderwerpen die verwerkt kunnen worden in het adviesrapport. Dit is te vinden in General>Adviesdocument>plan voor adviesplan.docx
Deze koppen zijn overgenomen in het adviesrapport V0.3

Het doornemen van de protfolio's duurde. 3 uur in totaal.
