### ISSUE TITLE
Verifying quality for dataset inventarisatie activiteiten

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#12]

**Comment by kcpveen** [comment]
@Nienkedn @HasinaNoori Zouden jullie een beschrijving hierbij willen plaatsen? Wij komen namelijk niet op een goeie.

**Comment by HasinaNoori** [comment]
Beschrijving issue: Gegevens onderzoeken met als doel eventuele problemen met de gegevenskwaliteit te identificeren en de mogelijke vervolgstappen die met de data ondernomen kunnen worden, beschrijven.
