### ISSUE TITLE
Van het overzicht een eerste opzet voor het BPMN maken

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#120]
Overzicht maken van welke actoren welke acties uitvoeren, wat voor looptijd hier aan vast zit, of dit een keuze is of leidt tot een keuze en welke stakeholders betrokken worden.

**Comment by GoldMercy** [comment]
Overzicht maken van welke actoren welke acties uitvoeren, wat voor looptijd hier aan vast zit, of dit een keuze is of leidt tot een keuze en welke stakeholders betrokken worden.

**Comment by szra0003** [comment]
Uit de interviews zijn de acties van het proces gehaald en verwerkt in een document. Het document is gevonden in teams onder: "BPMN/Opzet BPMN.docx". De besteedde tijd is 6,5 uur in totaal.
