### ISSUE TITLE
Demo maken sprint 5

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#121]
Maak een demo van Sprint 5 om op 17 november aan Anne te geven.
bepaal ook wie deze gaat geven

**Comment by LeCanard272** [comment]
deze demo wordt gegeven voor meer mensen. pascal, stephan, mischa en esther zijn er ook bij. 
Deze demo gebruiken we om in 1 moment iedereen op de hoogte te brengen van de status van het project. 
Wat moet er verteld worden in deze demo: 

- Korte uitleg van het project voor de leken
- wat hebben we tot nu toe bereikt vanaf sprint 0 (tussenresultaten) , en voortgang bereikt afgelopen sprint
- hoe gaan we te werk (communiceren, github ticketing, team rollen en verdeling)
- vervolgstappen

**Comment by kcpveen** [comment]
Presentatie demo af, straks reviewen met team.

2.5 uur aan gewerkt.

**Comment by HasinaNoori** [comment]
Vervolgstappen van adviesplan moeten worden toegevoegd. Voor de rest af en gevalideerd met het team. In totaal 2,5 x 2 = 5 uur plus 1 uur validatie = 6 uur in totaal. Demo staat op teams. In de map Agile -> sprint 5.

**Comment by roel0064** [comment]
Vervolgstappen van het adviesplan zijn toegevoegd
