### ISSUE TITLE
Opdracht Pascal

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#127]
Pascal heeft een opdracht gegeven aan alle trackers van de opleiding.

Hij heeft aan alle groepjes gevraagd of zij een simpele maar schematische visualisatie kunnen maken over de flow van een klantvraag naar user story naar een oplossing. Wie komt daar bij kijken en wie doet wat.
Hierbij moet nadrukkelijk gelet worden op : wat is de impact van een actie van een rol op een andere rol.
en waar een rol verantwoordelijk voor is in het proces en wanneer deze persoon 'geactiveerd wordt'

Deze moet bij de eerstvolgende trackermeeting gepresenteerd worden. 

Link naar de opdracht: https://drive.google.com/file/d/133RBo9H2Rna7BJohRrzNWZeP2KAdy43n/view?usp=sharing

**Comment by kcpveen** [comment]
Eerste opzet gemaakt.
De tracket swimlane moet nog voltooid worden en die van de developer, daarna moet alles netjes gemaakt worden.

Nu 2 uur aan gewerkt

**Comment by LeCanard272** [comment]
Is afgemaakt. We hebben de BPMN verder uitgewerkt en presenteerbaar gemaakt.
Er is een jpeg  en de XML opgeslagen in TEAMS\HZ University of Applied Sciences\B.A.U. Consultants - General\Agile
1u * 3 + 2 van kevin erbij is 5 uur totaal.
