### ISSUE TITLE
Eerste opzet van BPMN schema's

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#128]
Er worden concepten van BPMN schema's opgesteld voor de volgende processen:
- Beleid en Strategie
- Evaluatie
- Projectrealisatie
- Kaderstelling en programmeren

**Comment by GoldMercy** [comment]
12 november 's ochtends 4 uur in totaal aan gewerkt

**Comment by GoldMercy** [comment]
12 november 's middags 1.5 in totaal aan gewerkt. Totaal staat nu op 5.5 uur.
Processen voor Projectrealisatie, Evaluatie en Beleid en Strategie zijn zo goed als klaar voor validering.

**Comment by LeCanard272** [comment]
bpmn schema kan in hst 4.3.2  van het adviesrapport gezet worden. als deze af is

**Comment by szra0003** [comment]
BPMN Schema's van Evaluatie en Kaderstelling & programmeren zijn afgerond. Er zijn hiervoor 2 documenten gemaakt. Deze staan op teams in de map general/BPMN. De besteedde tijd op 19 Novemeber is 5,5 uur.
