### ISSUE TITLE
BPMN voor Onderhoud & Bedienen uitsturen voor validatie

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#131]

**Comment by LeCanard272** [comment]
graag de wat-vraag nog invullen bij aanvang ticket @GoldMercy @szra0003

**Comment by roel0064** [comment]
Mail is de deur uit gestuurd. ~30 min mee bezig geweest

**Comment by LeCanard272** [comment]
nog geen reactie ontvangen. Reminder gestuurf zojuist

**Comment by KylianLauerHZICT** [comment]
we kunnen vanmiddag of vanavond een reactie op de mail ontvangen
