### ISSUE TITLE
BPMN voor Vergunningverlening uitsturen voor validatie

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#132]

**Comment by LeCanard272** [comment]
graag de wat-vraag nog invullen bij aanvang ticket @GoldMercy @szra0003

**Comment by LeCanard272** [comment]
wat: De gemaakte BPMN uitwerking van het interview terugsturen naar Esther en deze valideren op correctheid.

**Comment by LeCanard272** [comment]
is gedaan. Heb zojuist een email gestuurd met daarin het BPMN schema, en de uitwerking hiervan. 
tim, rik en niels in CC.
20 min mee bezig.
