### ISSUE TITLE
BPMN voor Projectrealisatie uitgestuurd voor validatie

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#133]

**Comment by GoldMercy** [comment]
Uitgestuurd en we wachten op feedback.

**Comment by LeCanard272** [comment]
is reminder gestuurd vanochtend. even reopen en terug naar review voor de standdown. 
we kunnen vanmiddag of vanavond nog reactie verwachten op de mail die gestuurd is.
