### ISSUE TITLE
Eerste opzet BPMN Onderhoud & Bedienen

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#135]
Tim: aan de hand van de informatie uit het interview met Pieter en Bart (RC's onderhoud en bedienen), een eerste opzet van een BPMN maken.

**Comment by LeCanard272** [comment]
graag de wat-vraag nog invullen bij aanvang ticket @GoldMercy @szra0003

**Comment by roel0064** [comment]
Eerste verise van het BPMN gemaakt. ~2 uur mee bezig geweest.
Er zijn nog een aantal onzekerheden die ik ga verwerken met ticket #131 

Uitwerking is te vinden in:
General>BPMN>BPMN Onderhoud en Bedienen
