### ISSUE TITLE
Eerste opzet BPMN Vergunningverlening

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#136]

**Comment by LeCanard272** [comment]
graag de wat-vraag nog invullen bij aanvang ticket @GoldMercy @szra0003

**Comment by LeCanard272** [comment]
wat: de BPMN schema maken, aan de hand van de uitkomsten van het interview van Esther bij vergunningsverlening. zie #137

**Comment by LeCanard272** [comment]
het bpmn schema en uitwerking is gemaakt.
 deze staan in Onedrive\HZ University of Applied Sciences\B.A.U. Consultants - General\BPMN\BPMN Vergunningverlening.
1,5 uur mee bezig geweest
