### ISSUE TITLE
Interview Vergunningverlening uitwerken

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#137]

**Comment by LeCanard272** [comment]
is voor het BPMN

**Comment by LeCanard272** [comment]
wat: het interview resultaat opsporen , deze uitwerken in de projectdocumentatie, en deze gereed maken voor starten BPMN

**Comment by LeCanard272** [comment]
is uitgevoerd. 
Hoe: interview resultaten verzameld. Nieuw document gemaakt met de uitkomsten vastgelegd. Deze kan gebruikt worden voor de verdere ontwikkeling van het BPMN donderdag #136

**Comment by LeCanard272** [comment]
uurtje mee bezig geweest.
uitwerking staat in onedrive\HZ University of Applied Sciences\B.A.U. Consultants - General\Interviews waterschap\Uitgewerkt interview Esther Vergunnigsverlening.docx

het oude bestand heb ik direct verwijderd.
