### ISSUE TITLE
Interview Onderhoud & Bedienen uitwerken

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#139]
Tim: Aan de hand van het interviewresultaat een uitwerking maken zodat hier later een BPMN van gemaakt kan worden.

**Comment by LeCanard272** [comment]
is voor het BPMN

**Comment by roel0064** [comment]
Het interview is 50 min lang. Dit gaat wat tijd kosten. Misschien is een M net niet genoeg, maar het is te vroeg om hier een uitspraak over te maken.

**Comment by LeCanard272** [comment]
dan krijg je een dikke L van mij

**Comment by roel0064** [comment]
~1.5 uur aan besteed. Ben net na de 16min mark. Nog 34min te gaan. 

Werk is al te zien onder: General > Interviews waterschapInterviews waterschap > Afgenomen interviews > Interview van Onderhoud en Bedienen RC's

**Comment by roel0064** [comment]
De laatste 34min opgesplitst met Niels. Splitsing is op de 33:40 mark.

~1 uur besteed aan mijn helft van deze splitsing. 
Uitwerking is toegevoegd aan het al bestaande bestand.

**Comment by szra0003** [comment]
2de gedeelte verwerkt in het document.
~1,5 aan besteed.
