### ISSUE TITLE
Doelstelling met Lidwien van DFD bespreken

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#140]

**Comment by LeCanard272** [comment]
Hoe: We hebben besloten dat we de meegestuurde informatie in de mail te herzien en deze opnieuw te sturen. 
We stellen een deadline (volgens advies pascal ;) voor woensdag. Als we dan nietss gehoord hebben gaan we er vanuit dat ze akkoord zijn.

**Comment by LeCanard272** [comment]
check #58 voor meer info about dfd

**Comment by roel0064** [comment]
Mail gestuurd naar Lidwien en Anne ter verheldering. Hierbij ook de mogelijkheid gegeven tot een meeting als het nog steeds niet helder is. 

~ 2 * 30 min bezig geweest. (1 uur)
