### ISSUE TITLE
Gewenste situatie uit de interviews analyseren

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#141]

**Comment by roel0064** [comment]
Ik heb alle aandachtspunten gerelateerd aan de ISM of de data(flow) naar de ISM in een lijst gezet om deze tot een totaalbeeld te vormen van de gewenste situatie. Het doorspitten van de interviews voor deze lijst heeft me 1,5 uur gekost. Werkelijk gewenste situatie is nog niet gedefinieerd.

**Comment by roel0064** [comment]
Volgens mee heeft dit ticket alleen betrekking tot het data vergaren voor hoofdstuk "4.7 Gewenste situatie" dit is gebeurd dus ik sleep de ticket naar review.
