### ISSUE TITLE
Visualisaties maken met zelfgemaakte ISM dataset

### ISSUE THREAD

**Issue by Nienkedn** [GoldMercy/B.A.U.-Consultants#142]
In Tableau moeten er visualisaties gemaakt worden die uiteindelijk in het dashboard terecht moeten komen. De dataset die Kevin heeft gemaakt wordt hiervoor gebruikt.

**Comment by LeCanard272** [comment]
onderdeel hiervan is #150 . 
(aangepast in refinement )

**Comment by kcpveen** [comment]
Met de hulp van rik heb ik de volgende grafieken gemaakt:

![image](https://user-images.githubusercontent.com/36401158/100107258-c2d33f00-2e69-11eb-9600-3e179b895ef5.png)

![image](https://user-images.githubusercontent.com/36401158/100107324-d1b9f180-2e69-11eb-832c-de84cdb52abc.png)

@GoldMercy en ik hebben hier 4 uur in totaal aan gewerkt.

**Comment by LeCanard272** [comment]
deze ticket is onderdeel van #149

**Comment by kcpveen** [comment]
Laatste grafiek gemaakt. 
Deze toont de percentage van de realisatie sep aan per PI.
De Tableau file staat in: "General\Dashboard\Data voor dashboard\Grafieken - ISM data (Rik en Kevin).twb"

![image](https://user-images.githubusercontent.com/36401158/100363160-a582aa00-2ffc-11eb-82a5-a48aee09adb4.png)

Hier nog 3.5 uur aan gewerkt
