### ISSUE TITLE
Huidige situatie uit de interviews analyseren

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#143]

**Comment by LeCanard272** [comment]
wat: de gehouden interviews inlezen om meer informatie naar boven te halen, die we kunnen gebruiken voor de huidige situatie verder te omschrijven voor issue #147

**Comment by roel0064** [comment]
Hoofdstuk 4.1 "Omschrijving huidige situatie" is op een globaal niveau beschreven. Het overkoepelende hoofstuk 4 "Analyse huidige situatie" is nog niet voltooid.
1 uur bezig geweest.

(Wrong place)

**Comment by LeCanard272** [comment]
Analyse is gedaan o.b.v de interviews. Deze informatie wordt direct in het adviesrapport gezet. 3 uur in totaal aan gewerkt.
