### ISSUE TITLE
Brainstormen over wat er gevisualiseerd moet worden

### ISSUE THREAD

**Issue by Nienkedn** [GoldMercy/B.A.U.-Consultants#144]
Het dashboard team moet gaan nadenken over wat er precies in het dashboard moet komen en wat voor soort data daarvoor nodig is.

**Comment by Nienkedn** [comment]
We hebben 3x1 uur overleg gehad. We hebben een overzicht van wat we willen visualiseren en wat we daarvoor nodig hebben. We gaan ieder verder met 1 programma om te experimenteren met het visualiseren.

**Comment by kcpveen** [comment]
1.5 uur aangwerkt om uit te zoeken wat mogelijk zou zijn met de ISM data maar ik heb nog geen goed resultaat kunnen boeken.

**Comment by Nienkedn** [comment]
3 uur gewerkt aan deze issue om te onderzoeken hoe visualisaties voor het programma waterkeringen gemaakt kunnen worden.

**Comment by HasinaNoori** [comment]
Begin gemaakt aan Tableau cursus en materiaal waar kon toegepast op ISM data. 3,5 uur aan gewerkt. Er is gebrainstormd en de vervolgstappen zijn duidelijk. Elke deelnemer zal met één programma te werk gaan en bevindingen worden later met elkaar uitgewisseld. Deze taken worden in nieuwe tickets opgepakt. Deze issue is afgerond.
