### ISSUE TITLE
Demo voor sprint 6 maken

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#145]
Wat:  we moeten een demo maken voor de opdrachtgever, die we dinsdag 1 december 13:00 uur kunnen geven

**Comment by LeCanard272** [comment]
De demo is verplaatst naar 8 december 09:30 ivm afwezigheid anne

**Comment by Nienkedn** [comment]
Ik heb de demo gemaakt. Hij staat onder agile -> sprint 6 -> demo. De dia van het adviesrapport heb ik niet kunnen invullen zou fijn zijn als iemand anders die op wil pakken of mij informatie wil geven ervoor. 60 min. mee bezig geweest.
