### ISSUE TITLE
Retrospective terugkijken en opdracht uitvoeren

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#146]
Wat: Pascal heeft ons de opdracht gegeven om de retro en de demo terug te kijken met het team. 
Hierbij moeten we onszelf reviewen en een lijst maken met bespreekbare punten. (als in tip en top methode) 
Deze punten kunnen we dan bespreken met (pascal?) voor feedback ed.

**Comment by LeCanard272** [comment]
oh, en apparantly is de opname van de demo verpest. Deze hebben we dus niet meer te doen ;) De retro kan nog wel teruggekeken worden

**Comment by roel0064** [comment]
Audio channel van de demo collapsed na een aantal minuten. OBS heeft daarna het verkeerde audio output device geselecteerd. Oopsy daisy

**Comment by LeCanard272** [comment]
gepland voor dinsdag na de retro.
wellicht is het een goed idee om de nieuwe retro op te nemen en te voorzien van onze mening ipv die van een paar weken terug

**Comment by Nienkedn** [comment]
Iedereen heeft individueel de retro teruggekeken en vervolgens hebben we allemaal tips en tops opgesteld. Deze punten hebben we vervolgens met elkaar gedeeld in een online meeting en zijn terug te vinden in het project board 'reviews sprint 5'.

**Comment by LeCanard272** [comment]
in de trackermeeting ga ik met pascal even overleggen hoe nu verder
