### ISSUE TITLE
Hoofdstuk 4 Adviesrapport

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#147]
wat: het adviesrapport moet verder uitgewerkt worden. Hierbij kunnen we verder werken aan het hoofdstuk 4

- [x] 4.1 UITKOMSTEN INTERVIEWS	
- [x] 4.2 OMSCHRIJVING HUIDIGE SITUATIE (IST)	
- [x] 4.3 AANLEIDING EN PROBLEEMSTELLING	
- [x] 4.4 PROCESSTROMEN HUIDIGE SITUATIE	
- [x] 4.5 KNELPUNTEN IN HET PROCES
- [x] 4.6 OMSCHRIJVING NOODZAAK VERANDERING	
- [x] 4.7 GEWENSTE SITUATIE (SOLL)	
- [x] 4.8 DOELSTELLING	
- [x] 4.9 KANSEN EN RISICO’S

	

hiervoor moet wel eerst geanalyseerd worden volgens #141 en #143 

EDIT: nieuwe indeling hoofdstuk (24-11-2020)

**Comment by roel0064** [comment]
Hoofdstuk 4.1 en 4.4 zijn uitgewerkt en te vinden in het adviesrapport. ~ 2 * 1 uur besteed. (2 uur totaal).

**Comment by LeCanard272** [comment]
ik heb de wat vraag bijgewerkt, door de nieuwe indeling als checklist toe te voegen.

**Comment by roel0064** [comment]
"Hoofdstuk 4.1 "Omschrijving huidige situatie" is op een globaal niveau beschreven. Het overkoepelende hoofstuk 4 "Analyse huidige situatie" is nog niet voltooid.
1 uur bezig geweest.

(Wrong place)" 

- Mijn comment onder issue "Huidige situatie uit de interviews analyseren" (19-11-2020)
Dit comment hoort hieronder te staan.
Verder is dit onderdeel verplaatst naar hoofdstuknummer 4.2 ipv 4.1

**Comment by roel0064** [comment]
Hoofdstuk 4.7 Gewenste situatie (SOLL) is gemaakt aan de hand van eerder vergaarde informatie uit de interviews. Ik heb ongeveer 1,5 uur besteed hieraan. 

(Misschien nog een keer handig dat deze doorgenomen wordt door iemand anders voor andere perspectieven of controle aangezien het hier om de gewenste situatie gaat.)

Edit: checkbox 4.7 bovenaan aangevinkt

**Comment by LeCanard272** [comment]
uitkomsten interviews, KPI mapping en noodzaak verandering is vastgelegd in het adviesrapport. De overige onderdelen die nog niet afgevinkt zijn moeten noggedaan worden of even verder aangevuld worden. Het BPMN moet er nog in gezet worden vanuit @GoldMercy @szra0003 kant.

+1.5u vanuit mijn kant is 6 uur totaal.

**Comment by LeCanard272** [comment]
4.2 af , Twee alinea's over KPI en programma's toegevoegd. +30 min

**Comment by roel0064** [comment]
Hoofdstuk 4.7 heeft een extra alina gekregen na aanleiding van feedback. ~20 min

**Comment by LeCanard272** [comment]
hoofdstuk 4.8 is gemaakt. doelstelling opgezet adhv wat we willen bereiken met dit project en wat we gaan opleveren.
Tim heeft een inleiding gemaakt voor hoofdstuk 4.5, waaraan verder gewerkt kan worden wanneer het BPMN af is. 

+ 1 uur erbij is 8 uur totaal.

**Comment by LeCanard272** [comment]
4.4 4.5 4.9 kunnen pas afgevinkt worden als de bpmn's klaar zijn.

**Comment by LeCanard272** [comment]
Sprint Goal sprint 7: Alle BPMN's erin geplaatst, kansen en risico's omschreven. Ticket dan pas sluiten

**Comment by LeCanard272** [comment]
even terug naar de backlog ivm hogere prio andere ticket

**Comment by roel0064** [comment]
4.4.2 BPMN Huidige situatie is uitgewerkt en verwijst nu naar de BPMNs in de bijlage. (nog niet alle BPMNs zijn aanwezig. Sommige hebben nog validatie nodig).

**Comment by roel0064** [comment]
6 uur in totaal besteed aan de afronding van hoofdstuk 4.
14 uur totaal.

Resultaat is te zien in:
General > adviesdocument > Adviesrapport V0.5.docx
