### ISSUE TITLE
Eerste concept Dashboard

### ISSUE THREAD

**Issue by HasinaNoori** [GoldMercy/B.A.U.-Consultants#149]
Alle deelnemers zullen tot donderdagmiddag individueel een dashboard proberen op te zetten in Tableau Desktop. Bevindingen zullen donderdagmiddag worden besproken. Donderdagmiddag zal de definitieve keuze worden gemaakt of we verder gaan met het dashboard of concluderen er geen dashboard opgesteld kan worden met de ISM data.

**Comment by HasinaNoori** [comment]
Tableau Desktop cursus t.e.m. hoofdstuk 4 doorgenomen en waar het kon toegepast op ISM data. 1 uur mee bezig geweest.

**Comment by Nienkedn** [comment]
Verder gegaan met de tableau cursus en ik heb in Tableau geexperimenteerd. 2 uur mee bezig geweest.

**Comment by HasinaNoori** [comment]
Tableau Desktop cursus afgerond. 3 uur mee bezig geweest. (op 25-11-2020)

**Comment by HasinaNoori** [comment]
Beginpagina dashboard gemaakt en uitkomsten functionele test doorgenomen. 3,5 uur mee bezig geweest. 

![image](https://user-images.githubusercontent.com/36400595/100361260-3c9a3280-2ffa-11eb-89ca-8534e3e2efa1.png)
