### ISSUE TITLE
Stakeholder map

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#15]

**Comment by LeCanard272** [comment]
in kaart brengen van de stakeholders en hun verantwoordelijkheden en belangen.

**Comment by LeCanard272** [comment]
on hold tot er meer input is

**Comment by LeCanard272** [comment]
opgepak 29-9-20 met @roel0064 en @szra0003

**Comment by szra0003** [comment]
We hebben de stakeholders in kaart gebracht. Deze is gedocumenteerd in stakeholder map.docx. Deze is te vinden op teams in folder business understanding. Duur van deze issue = 1,5 uur -> (dus 4,5 uur als team, omdat er met 3 man aan gewerkt is).
