### ISSUE TITLE
Starten hoofdstuk 6 (Adviesrapport) 

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#152]
wat: omdat we wat tijd over hebben na het schrijven van het hoofdstuk 4. en we moeten wachten op het bpmn, kunnen we vast starten met een begin te maken voor hoofdstuk 6. SCOPE
- [x] Financiëel
- [x] Afdelingen en personeel
- [x] Projecten
- [x] Processen
- [x] Betrekking management

**Comment by LeCanard272** [comment]
we laten het even weer doen, omdat we eerst niels gaan helpen met zijn tickets.

**Comment by LeCanard272** [comment]
is omgezet tot een sprint goal voor sprint 7

**Comment by LeCanard272** [comment]
bij aanvang wat vraag herformuleren

**Comment by KylianLauerHZICT** [comment]
we schrappen deze sprint goal ivm de tactical nuke die pascal heeft gedropt.

**Comment by roel0064** [comment]
Het hoofdstuk is af voor nu. Aan de hand van wat er tijdens de meeting met het MT nog gezegd wordt kan deze nog veranderd worden.De uitwerking is te zien in het adviesrapport v0.5 onder hoofdstuk 6.

1,5 uur * 3
4,5 uur totaal
