### ISSUE TITLE
Leerdoelen CPS beschrijven

### ISSUE THREAD

**Issue by Nienkedn** [GoldMercy/B.A.U.-Consultants#157]
Het tweede deel van onze CPS beoordeling is onderverdeeld in vier leerdoelen. In deze issue is een checklist te vinden die alle onderdelen van de vier leerdoelen weergeeft. Wanneer alle boxes een vinkje hebben dan  zouden we alles voor dit deel van CPS voldoende moeten hebben.

**Comment by Nienkedn** [comment]
Learning outcome 1: 
You clarify the company's current situation through coordinated KPIs and an obtained data set and you make an inventory of where the company can still take steps for improvement. Taking into account improvements in, among other things, new technologies.

- [x] 1.1 Er is een korte beschrijving van de doelstellingen en organisatie van de opdrachtgever
met de vakinhoudelijke kennis uit het ICT-domein. Het probleem is in kaart gebracht in
relatie tot de doelstellingen. 

- [x] 1.2 Je brengt het relevante bedrijfsproces op een gedegen en gestructureerde manier in
kaart hierbij rekening houdend met de informatiestromen.

- [x] 1.3 Je analyseert alle bedrijfsprocessen en informatiestromen en brengt daarbij de
knelpunten in kaart.

- [x] 1.4a Je hebt in kaart gebracht hoe je de knelpunten kan verhelpen, met inachtneming van de
eisen en wensen van de stakeholders.

- [x] 1.4b Je beargumenteert welke ICT-voorzieningen/diensten in aanmerking komen om je
oplossing te ondersteunen.

**Comment by Nienkedn** [comment]
Learning outcome 2:
You analyze the IST of the processes within the company and you come up with realistic improvement proposals based on the various models and your own vision (SOLL).

- [x] 2.1 Je hebt een gedegen selectieproces doorlopen met betrekking tot de ICT voorzieningen en
knelpunten. Op basis hiervan maak je een gevalideerd ontwerp voor het SOLL-proces. 

- [x] 2.2 Je ontwerp is toekomstbestendig, daarbij heb je o.a. rekening gehouden met
beheer/implementatie/optimalisatie.

- [x] 2.3 Je doet aanbevelingen voor de te implementeren oplossing(en).

**Comment by Nienkedn** [comment]
Learning outcome 3:
You realize and evaluate implementation (plan) and evaluate based on your own design, so the company has a ready-made plan to follow through with the implementation of the changes

- [x] 3.1 Het ontwerp is dusdanig opgesteld dat deze geïmplementeerd kan worden binnen het
bedrijf.

- [x] 3.2 Je maakt een acceptatietest voor de implementatie en laat deze uitvoeren door
verschillende stakeholders

- [x] 3.3 Beargumenteer welke veranderstrategie wel of niet van toepassing is.

**Comment by Nienkedn** [comment]
Learning outcome 4:
You advise in a well-argued manner the best option based on your own vision/core values, a theoretical change model and the core values of the company.

- [x] 4.1 Er is een voorstel uitgewerkt waarin relevante en goed onderbouwde (mogelijke)
vervolgacties zijn geformuleerd

- [x] 4.2 Al het materiaal is op een professionele manier overgedragen aan de opdrachtgever.

- [x] 4.3 Uit de opleiding aangereikte kennis (masterclasses) is op een correcte wijze toegepast

**Comment by HasinaNoori** [comment]
De learning outcomes geïnventariseerd. Degene die al behaald zijn heb ik afgevinkt. De argumentatie hiervoor is terug te vinden op Teams -> General -> CPS -> CPS learning outcomes geïnventariseerd. 45 minuten mee bezig geweest.

**Comment by LeCanard272** [comment]
we hebben per indicator bepaald wat we ervoor gaan doen, en het document van hasina bijgewerkt naar een grote to do list.

+ 3 uur

**Comment by LeCanard272** [comment]
alle learning outcomes zijn gedaan muv 4.2

**Comment by Nienkedn** [comment]
Hoofdstuk 4 heb ik dingen toegevoegd en ik heb de bijlages die we tot nu toe hebben toegevoegd aan het document. Vgm is het enige dat over is van H4 de veranderstrategie erin stoppen. 5 uu mee bezig geweest.
