### ISSUE TITLE
Interview medewerker automatisering inplannen

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#158]
Er moet contact gemaakt worden met de medewerker automatisering om een interview te plannen.

**Comment by kcpveen** [comment]
Ik heb een mail gestuurd naar Frank Westerink en hier moet hij nog op reageren.

1 uur aan gewerkt.

**Comment by kcpveen** [comment]
Interview afgelegd in een kwartier.

Aantekeningen staan in: Dashboard > Uitkomsten Automatisering Interview
