### ISSUE TITLE
Probleemstelling opstellen

### ISSUE THREAD

**Issue by kcpveen** [GoldMercy/B.A.U.-Consultants#16]

**Comment by LeCanard272** [comment]
Probleemstelling formuleren voor team 
uiteindelijk komt dit in het adviesrapport

**Comment by LeCanard272** [comment]
probleemstelling is overgenomen uit de documentatie van WSS.
Ter verduidelijking voor het team is per item in duidelijkere taal vermeldt wat er van ons verwacht worden.
