### ISSUE TITLE
Homescreen dashboard afmaken

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#162]
Het beginscherm van het dashboard moet afgemaakt worden. De grootte moet uitgekozen worden en de onderdelen moeten er op aangepast worden. Ook moet het beginscherm naar de juiste schermen gelinkt worden.

**Comment by HasinaNoori** [comment]
Beginscherm van het dashboard is afgemaakt. Er is gekozen voor de grootte full screen (1024 - 768). Voor elk programma is een dashboard scherm aangemaakt en door het klikken op een programma kom je in het juiste scherm terecht. Deze nieuwe versie is terug te vinden op teams General -> Dashboard -> Dashboard versie 0,3. 1 uur mee bezig geweest.
