### ISSUE TITLE
Programmapagina Afvalwaterketen invullen

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#165]
Vanuit het beginscherm kan naar een aparte pagina worden genavigeerd voor het programma Afvalwaterketen. Deze pagina moet worden ingevuld met de juiste onderdelen (grafieken & visualisaties).

**Comment by HasinaNoori** [comment]
2 uur aan gewerkt. Begin gemaakt aan de schermen voor Afvalwaterketen schermen. Na verleg met dashboard team voor een andere aanpak gekozen. Dit moet verder uitgewerkt worden.

**Comment by HasinaNoori** [comment]
Nieuwe versie is uitgewerkt. Hiervoor zijn meerdere schermen toegevoegd. Ook zijn er knoppen toegevoegd om van het ene scherm naar het andere scherm te kunnen klikken. Dit om het dashboard presenteerbaar te maken. Nog twee uur mee bezig geweest. Nieuwe versie is terug te vinden op Teams -> General -> Dashboard -> Dashboard demo versie 0,3.
