### ISSUE TITLE
Advies over de waarom vraag

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#172]
Er moet een stukje in het adviesrapport komen over waarom Waterschap Scheldestromen gebruik zou kunnen maken van een dashboard. 
CPS Learning outcome 2.3

**Comment by LeCanard272** [comment]
neem dit mee bij het schrijven van het advies.

Een knelpunt was : 	"Op het moment wordt door de financieel medewerker een Excel gemaakt die de budgethouders moeten invullen. Hierdoor wordt voor elke nieuwe iteratie van het proces een nieuw Excel bestand gemaakt. Dit veroorzaakt een onoverzichtelijke situatie waardoor informatie verkeerd geïnterpreteerd kan worden, of zelfs over het hoofd gezien kan worden. "

Anne gaf als feedback: 
"Is hier een specifieke reden voor, of is het echt een mogelijk verbeterpunt? Ik kan me voorstellen dat ze bij financiën er voor kiezen om een nieuw document te maken ter archivering, echter is dit inderdaad geen overzichtelijke situatie. Neem het mee in je advise; wat moet er intern gebeuren om dit soort dubbele stappen in het process te voorkomen. "

18 December 2020, 10:37

**Comment by HasinaNoori** [comment]
Deel is uitgeschreven. Moet in het adviesdocument worden gezet. Dan is ticket afgerond.
