### ISSUE TITLE
BPMN's plaatsen in het adviesrapport

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#173]
Wat: Wanneer alle bpmn's gevalideerd zijn, moeten we deze in het adviesrapport plaatsen. 

schema's in bijlage zetten. Algemene omschrijving in BPMN hoofdstuk 4 geven met verwijzingen.

**Comment by LeCanard272** [comment]
tot nu toe heb ik : 

Beleid en Strategievorming
Evaluatie
Kaderstelling en programmeren

In het adviesrapport gezet. 

to do: (eerst wachten op validatie)
Onderhoud en bedienen
projectrealisatie
vergunningsverlening

**Comment by roel0064** [comment]
Moet effe een reminder sturen

**Comment by LeCanard272** [comment]
Er is een reminder gestuurd naar Esther van vergunningsverlening. Ook onderhoud en bedienen is een reminder gestuurd. +15 min allemaal

**Comment by LeCanard272** [comment]
Esther is tot 4 januari out of office.

**Comment by roel0064** [comment]
Feedback gekregen nog niet verwerkt.

**Comment by LeCanard272** [comment]
Ik ga vanmiddag Projectrealisatie nog berichten.

**Comment by LeCanard272** [comment]
vergunningsverlening is toegevoegd, met een side note dat deze (nog) niet gevalideerd is. (esther is 4 januari pas terug)

**Comment by roel0064** [comment]
Onderhoud en bedienen is gevalideerd en aangepast. Deze is al in het rapport gestopt. Nog geen verdere uitleg toegevoegd. 15 min mee bezig geweest.

**Comment by LeCanard272** [comment]
Alleen Projectrealisatie moet nog aan het portfolio toegevoegd worden. (eerst validatie verwerken) #187

**Comment by LeCanard272** [comment]
projectrealisatie heb ik opgepakt. #187 
Deze is nu ook toegevoegd in het rapport. 
Alle BPMN's van de huidige situatie zijn in het rapport geplaatst. 
+5 min
