### ISSUE TITLE
Presentatie voor 11 en 14 december maken

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#174]
Moet een presentatie gemaakt worden die voor de Pascal opdracht van 11 december en de presentatie voor het MT van 14 december gebruikt kan worden.

WIP presentatie staat in de agile map onder "Presentatie MT"

**Comment by GoldMercy** [comment]
Uitlijning presentatie gemaakt, bekeken met dashboard team. 3 uur aan gewerkt.

**Comment by Nienkedn** [comment]
Presentatie voor docenten heb ik gemaakt. Op twee dia's na is deze 'klaar'. 2.5 uur mee bezig geweest

**Comment by GoldMercy** [comment]
Aantekeningen gemaakt over wat ik wil zeggen, dia's aangepast en structuur van de presentatie aangepast. Vandaag 3 uur aan bezig geweest

**Comment by roel0064** [comment]
De presentatie is gemaakt + voorbereid en er is feedback over gegeven. Deze feedback is verwerk en we zijn klaar voor 11 december.
+ nice drawings added

2 uur voor preparatie door presentators.
5 * 0,5 uur voor de review (2,5 totaal)
3 * 20 min voor nice drawings (1 uur)

**Comment by kcpveen** [comment]
Presetatie met stephan gehouden en de feedback verwerkt.

3u aan gewerkt met @roel0064

**Comment by roel0064** [comment]
Er moeten nog links gemaakt worden naar de data voor de presentatie (tableau stuff)
