### ISSUE TITLE
demo sprint 7 maken

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#175]
maak een demo voor sprint 7 voor anne

**Comment by HasinaNoori** [comment]
Gestart met demovoorbereiding betreft het maken van de presentatie.

**Comment by LeCanard272** [comment]
demo is zojuist afgemaakt. Kortere demo dit keer, maar wel veel voortgang geboekt. **In de standdown even overleggen wie deze kan geven morgen.** 
De demo staat in de  Onedrive\HZ University of Applied Sciences\B.A.U. Consultants - General\Agile\sprint 7 folder.
niet meer dan 1,5 uur aan besteed.
