### ISSUE TITLE
Planning voor oplevering opstellen

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#176]
Er moet een planning gemaakt worden voor de oplevering van het project.

**Comment by HasinaNoori** [comment]
Ik heb een korte mail opgesteld voor de opdrachtgever. Inhoud moet besproken worden met het team. Dit kan tijdens de stand-down.  1 uur mee bezig geweest.  Mail staat hieronder beschreven. 

Beste Anne, 

Hierbij stuur ik een globaal overzicht van wat wij de komende periode graag zouden willen ontvangen. Ook zijn andere momenten hieronder beschreven.

-	Week 51: Feedback op het adviesrapport. 
-	Week 52: Deze week zijn wij bezig met het afronden van de competenties. 
-	Week 53: Deze week zijn wij bezig met het afronden van de competenties.
-	Week 1: Ingevuld beoordelingsformulier. Het lijkt ons een goed idee om deze na de demo samen door te nemen. De demo zal binnenkort worden ingepland. 
-	Week 2: Eventueel een meeting om de laatste vragen/opmerkingen door te spreken. 
-	Week 3: Project overdracht. Deze zullen wij in overleg plannen en inrichten. 
-	Week 4: Demo & Go event. Dit event staat op 29 januari gepland en is georganiseerd vanuit de HZ. Jullie zijn van harte welkom om hierbij aan te sluiten! 

Het beoordelingsformulier en het adviesrapport zijn als bijlage meegestuurd. Mochten er vragen en/of opmerkingen zijn, hoor ik dat graag terug. Als je het idee hebt dat er zaken niet haalbaar zijn, kunnen wij dit eventueel samen proberen op te lossen. 

Met vriendelijke groet, 	

Hasina Noori
B.A.U. Consultants

**Comment by roel0064** [comment]
Ticket objective is nog niet helemaal duidelijk.

**Comment by LeCanard272** [comment]
wordt verder opgepakt in sprint #196
