### ISSUE TITLE
Hoofdstuk 5.1.1 schrijven

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#177]
Wat: schrijf hoofdstuk 5.1.1 van het adviesrapport. Dit gaat over de oplossing van de opgespoorde knelpunten. 

5.1.2 niet die doet het dashboard team.

**Comment by roel0064** [comment]
We hebben voor hoofdstuk 5.1.1 de verhelping van knelpunten beschreven.

1 * 3 uur aan besteed
3 uur totaal.
