### ISSUE TITLE
Hoofdstuk 7 Veranderstrategie invullen

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#179]
Hoofdstuk 7 Veranderstrategie moet ingevuld worden wat direct helpt voor Learning outcome 3 van CPS

**Comment by GoldMercy** [comment]
Vandaag Rik en Kylian en 2 uur aan gewerkt.

**Comment by GoldMercy** [comment]
Vanochtend en voor 15.00 3 uur aan gewerkt. Zal na de vergadering van 15.00 - 16.00 verdergaan en zal daarna geupload worden in de map "Adviesdocument". Zal aan het einde van de middag nog een comment plaatsen met wat er wel en niet gedaan is.

**Comment by LeCanard272** [comment]
ik heb hoofdstuk zeven voor zover ik dat kan ingevuld. rik werkt aan het schema. 
+5 = 8

**Comment by GoldMercy** [comment]
Na de vergadering nog half uurtje aan gewerkt om in ieder geval een algemeen leeg veranderschema opgesteld te krijgen gebaseerd op de Acht stappen van Kotter. Te vinden in General > Veranderplannen voorbeelden onder "Veranderschema - Waterschap Scheldestromen". **Is dus op een andere locatie dat wat ik in de vorige comment voorstelde.** Vond hem hier meer gepast.

Het idee is nog om het schema wat meer om te zetten naar een schema dat termen uit de organisatie van Waterschap Scheldestromen gebruikt. Daarnaast nog een goed idee het schema uit te schrijven om extra toelichtingen te geven hier en daar.

+0.5 = 8.5

**Comment by GoldMercy** [comment]
Vandaag 4.5 uur bezig geweest met het contextualiseren van het veranderschema en het veranderschema uit te schrijven.

+4.5 = 13
