### ISSUE TITLE
DFD Ontwerpen

### ISSUE THREAD

**Issue by kcpveen** [GoldMercy/B.A.U.-Consultants#18]
Een dfd die inzichtelijk maakt hoe de data van de resultaatcoördinatoren tot en met de stuurhut stroomt.

**Comment by GoldMercy** [comment]
Het opstellen van een DFD om inzichtelijk te maken hoe de data naar de stuurhut stroomt.

**Dit is een DFD, Dit is niet een BPMN schema**

**Comment by LeCanard272** [comment]
ik ben bezig met informatie bij elkaar sprokkelen uit de interviews die kan helpen bij het maken van de DFD.
DFD maken zal in sprint 4 wel gebeuren schat ik.

**Comment by LeCanard272** [comment]
check issue #116 voor info.

**Comment by LeCanard272** [comment]
Heb een flow gemaakt van hoe de informatie op de ISM komt.
dit gebaseerd op de interviews die gedaan zijn.
Staat in Teams\HZ University of Applied Sciences\B.A.U. Consultants - General\DFD's
Denk klein uur mee bezig geweest.

please review when able to

**Comment by LeCanard272** [comment]
bovengenoemd bestand omvormen tot een DFD model (voor zover dat kan)

**Comment by LeCanard272** [comment]
aanvulling: het eerdere inforstroom diagram omvormen tot een klassieke DFD, voor zover dat mogelijk is.

**Comment by LeCanard272** [comment]
het Diagram is omgezet naar een DFD. Deze is ook gelijk in het adviesrapport geplaast, met begeleidende tekst. 
Graag reviewen vanmiddag 15:30 

het DFD staat in : TEAMS\HZ University of Applied Sciences\B.A.U. Consultants - General\DFD's

2 uur en 15 minuten * 2 = 4.5 uur aan gewerkt
