### ISSUE TITLE
Pakketselectie opstellen

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#180]
Er moet een pakketselectie opgesteld worden waar een keuze voor een datavisualisatie applicatie in gemaakt wordt. Er moet rekening gehouden worden met welke IT systemen Waterschap Scheldestromen nu werkt. Dit is direct toepasbaar op learning outcome 1.4b en als uitbreiding op 1.1.

**Comment by kcpveen** [comment]
IST omschreven.

1 uur aan gewerkt.

Volgende stappen zijn de soll beschrijven

**Comment by kcpveen** [comment]
In het advies document heb ik een Bijlage 2: Softwarepakket selectie toegevoegd.
Hierin worden vier softwarepakketten aangehaald. Hiervan worden pepperflow en ArcGIS direct omschreven dat ze niet voldoen aan de minimum eisen.
De knock-out criteria's en wegingen zijn omschreven en uitgelegd.
Het knock-out schema is af waarin PowerBI de winnaar is.

Wat moet er nog gedaan worden?:
- Het resultaat van de criteria's moeten worden beschreven. Bijvoorbeeld waarom het een speciefieke weging heeft en waarom het zo heeft gescoord in het knock-out schema.
- PowerBI moet dan nog in het advies komen te staan.

Vandaag 5 uren aan gewerkt waardoor de grootte van deze issue vergroot wordt naar een "L"

**Comment by kcpveen** [comment]
Zodra dit af is vergelijken met "CPS learning outcomes geïnventariseerd" document om te kijken welke leerdoelen ik hiermee heb behaald. Indien er missen deze ook behandelen in het advies document.

**Comment by kcpveen** [comment]
Bijlage 2: Pakketselectie is afgerond.

Hier 2 uren aan gewerkt

**Comment by kcpveen** [comment]
5.2.1 Pakketsekectie is ook afgerond.
Hier 0.5 uur aangewerkt.
Totaal 8.5u aan deze issue gewerkt. Vandaar de size veranderd naar XL.

Pakketselectie is hierbij afgerond en klaar voor review.

**Comment by kcpveen** [comment]
Ik heb nog even de bronnen van tableau en Microsoft in de tekst erbij gezet en in APA vorm in de literatuurlijst. @KylianLauerHZICT
