### ISSUE TITLE
Dashboard .zip pakket controleren

### ISSUE THREAD

**Issue by kcpveen** [GoldMercy/B.A.U.-Consultants#182]
@kcpveen heeft een het dashboard gekoppeld en in een .zip ("Dashboard demo versie (Uploaded door Kevin).zip") gedaan. Deze moet iemand even controleren of het bij hun direct werkt en of het uiterlijk klopt. Indien iets in het uiterlijk niet klopt moet dit mee genomen worden in een issue voor het dashboard.
De .zip is gebaseerd op @HasinaNoori haar dashboard pakketje.

**Comment by HasinaNoori** [comment]
ZIp bestand gecontroleerd. Dashboard werkt correct en het uiterlijk klopt bij het openen. 20 min aan gewerkt.
