### ISSUE TITLE
Acceptatietest voor de implementatie

### ISSUE THREAD

**Issue by roel0064** [GoldMercy/B.A.U.-Consultants#186]
Acceptatietest maken voor de impementatie. Deze aan meerdere type stakeholders sturen.

**Comment by LeCanard272** [comment]
Onderstaand bericht wordt verstuurd naar Anne, Lidwien en Ivan. (3 verschillende rollen) 
Ook is iedereen in de CC bijgevoegd. we zijn hier 2 uur aan kwijt geweest. 
Het te valideren stuk staat in Onedrive\HZ University of Applied Sciences\B.A.U. Consultants - General\Validatie veranderstrategie , samen met het schema.

![image](https://user-images.githubusercontent.com/36400283/102892603-6a8b5f00-4460-11eb-8953-c132d2064b07.png)
