### ISSUE TITLE
Validatie Anne verwerken in acceptatietest

### ISSUE THREAD

**Issue by roel0064** [GoldMercy/B.A.U.-Consultants#195]
We hebben feedback van Anne verkegen tijdens de vakantie aan de hand van de eerste acceptatietest. Deze feedback moet verwerkt worden.

**Comment by LeCanard272** [comment]
![image](https://user-images.githubusercontent.com/36400283/103353633-997d8280-4aa9-11eb-8028-f5cbb2d670a4.png)

**Comment by LeCanard272** [comment]
wij hebben het implementatieplan van het veranderstrategie voorzien van haar feedback. Deze is direct verwerkt in hoofdstuk 7 van het adviesrapport. We hebben de onderstaande mail weer teruggestuurd naar alle betrokkenen. totaal  2 uur en 40 min mee bezig geweest 
![image](https://user-images.githubusercontent.com/36400283/103353738-e2353b80-4aa9-11eb-8aec-800d38b9b627.png)
