### ISSUE TITLE
Presentatie opdrachtgever maken

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#206]
Presentatie maken voor de opdrachtgever betreft overdracht project

**Comment by HasinaNoori** [comment]
Presentatie opzet is opgesteld en grotendeels ingevuld. In verband met onzekerheid over de noodzaak van deze presentatie bij de opdrachtgever, wordt een mail afgewacht voordat deze verder wordt afgemaakt. Presentatie staat op Teams -> Bestanden -> Eindpresentatie opdrachtgever. Ongeveer 4 uur aan gewerkt.

**Comment by GoldMercy** [comment]
Geclosed gezien niet meer van toepassing
