### ISSUE TITLE
Afbakening Scope

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#26]
Helder formuleren wat onze projectscope is voor de komende sprints.

**Comment by LeCanard272** [comment]
ge - herformuleerd in een overzichtelijker en beter begrijpbaar is. 
Please kijken of dit nog conform is met de nieuwe scope met Lidwien en Anne

**Comment by HasinaNoori** [comment]
Dit onderdeel mag verder uitgewerkt worden. Verdere documentatie van de scope o.a. de mijlpalen moeten aangepast worden en toegevoegd worden.

**Comment by LeCanard272** [comment]
kevin en rik pakken dit op

**Comment by GoldMercy** [comment]
Uiteindelijk 2 uur mee bezig geweest. Taalgebruik verbeterd. Onnodige deelvragen weggehaald.

**Comment by roel0064** [comment]
Ik wil de ticket nooit meer zien - Rik
