### ISSUE TITLE
Link zoeken tussen sturingsmonitor en Inventarisatie Activiteiten dataset

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#28]

**Comment by kcpveen** [comment]
@Nienkedn @HasinaNoori Hebben jullie deze issue niet al afgerond?

**Comment by HasinaNoori** [comment]
Beschrijving issue: Gegevenskwaliteit verifiëren door te terug te koppelen naar de hoofdvraag en uit te zoeken hoe de data kan bijdragen bij het beantwoorden van de hoofdvraag.
