### ISSUE TITLE
Interview dataset WS Basislijst Projecten houden

### ISSUE THREAD

**Issue by roel0064** [GoldMercy/B.A.U.-Consultants#33]
Interview om de data uit WS Basislijst Projecten.xlsm te verhelderen.

**Comment by roel0064** [comment]
Interview was gepland op deze dag, maar is uitgesteld door een probleem aan Jo zijn kant.

**Comment by LeCanard272** [comment]
interview gehouden met jo nieuwenhuize over de inventarisatie activiteiten.
Basislijst projecten 
kan starten met uitwerken #49
