### ISSUE TITLE
Prestatie-indicator (PI)

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#34]
Het opstellen van interne procesgerelateerde PI's uit bestaande datasets. De PI's moeten zich richten op hoe processen uitgevoerd worden binnen Waterschap Scheldestromen. Er zijn bepaalde datasets aanwezig waar nog geen PI's over gedefinieerd zijn.

**Comment by kcpveen** [comment]
N.V.T.
