### ISSUE TITLE
Find a way to get a grip on project hour demand and supply

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#36]
create a overview for myself and the team to easily view the amount of projecthours demanded by the project and the amount supplied by the team.

**Comment by HasinaNoori** [comment]
Verdere onderzoek naar goede manier van bijhouden van ongeplande projectwerk is nodig.

**Comment by LeCanard272** [comment]
Voor nu wordt een marge aangehouden voor "ongedocumenteerd projectwerk"
Denk aan als iemand de ruimte binnen komt lopen om een gesprek te houden met ons, en we daardoor projecttijd niet kunnen verantwoorden.  

Also: we hebben besloten dat de 2e woensdag in een sprint als zelfstudie geldt ivm te veel projecturen. (hier kunnen we nog wel flexibel in zijn)
