### ISSUE TITLE
Organogram maken

### ISSUE THREAD

**Issue by kcpveen** [GoldMercy/B.A.U.-Consultants#38]
Er moet een organogram gemaakt worden van de organisatiestructuur om te kunnen zien wat de verbanden zijn tussen de verschillende functies, afdelingen en organisatie lagen die te maken hebben met het project.

**Comment by GoldMercy** [comment]
Schets met validatie met Anne - 1,5 uur

**Comment by GoldMercy** [comment]
1 uur extra in de ochtend van 24 sept

**Comment by LeCanard272** [comment]
het organogram is gemaakt en uitgeschreven met betekenissen.
Moet nu reviewen met Anne Dekker . #59
