### ISSUE TITLE
Interview dataset WS Basislijst Projecten uitwerken

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#49]

**Comment by Nienkedn** [comment]
Het interview uitwerken door de antwoorden bij de interview vragen te zetten.

**Comment by roel0064** [comment]
Bevindingen achteraf direct in de data understanding van  WS Basislijst Projecten gezet.
~30 min werk.

**Comment by roel0064** [comment]
Bevindingen achteraf met het team gedeeld.
~15 min (* 7 man)
