### ISSUE TITLE
Demo Sprint 2 maken

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#52]
Maak een presentatie voor de demo van sprint 2.

**Comment by roel0064** [comment]
Er moeten nog een aantal assets toegevoegd worden.
~20min * 5 so far.

**Comment by LeCanard272** [comment]
Demo is ondertussen al gemaakt en gegeven.
geen idee hoelang we hier mee bezig geweest zijn.
