### ISSUE TITLE
Interview dataset inventarisatie activiteiten houden

### ISSUE THREAD

**Issue by Nienkedn** [GoldMercy/B.A.U.-Consultants#54]
Interview om de dataset inventarisatie activiteiten te verhelderen.

**Comment by Nienkedn** [comment]
We hebben de vragen die wij hadden over deze dataset aan Tim gegeven zodat hij deze tegelijkertijd met zijn eigen vragen kan stellen.

**Comment by roel0064** [comment]
~ 5min toelichting gegeven
