### ISSUE TITLE
Interview dataset inventarisatie activiteiten uitwerken 

### ISSUE THREAD

**Issue by Nienkedn** [GoldMercy/B.A.U.-Consultants#55]
Het interview uitwerken door de antwoorden bij de interview vragen te zetten.

**Comment by Nienkedn** [comment]
Omdat Tim onze vragen in zijn interview heeft meegenomen hebben wij geen interview hoeven uitschrijven.

**Comment by roel0064** [comment]
~ 5min toelichting gegeven
