### ISSUE TITLE
Interview dataset inventarisatie activiteiten verwerken 

### ISSUE THREAD

**Issue by Nienkedn** [GoldMercy/B.A.U.-Consultants#57]
De antwoorden uit het interview implementeren in het data understanding bestand.

**Comment by Nienkedn** [comment]
Tim heeft de uitkomsten van het interview met ons gedeeld en deze heb ik meteen in ons data understanding document verwerkt.

**Comment by roel0064** [comment]
~5 min voor inlichten info
