### ISSUE TITLE
DFD valideren en bijwerken

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#58]

**Comment by LeCanard272** [comment]
valideren bij de opdrachtgever.

**Comment by LeCanard272** [comment]
zojuist afgesproken dat we het DFD op gaan sturen naar Anne en Lidwien voor validatie. Donderdag gaan we dit doen

**Comment by LeCanard272** [comment]
Validatie is per email verstuurd 09:48 12-11-2020 naar Anne en Lidiwien.
Zodra we antwoord hebben zullen we dit weer oppakken. 
Even naar review, en daarna kan deze terug op ON HOLD for now.

1 uur max aan gewerkt tot nu toe.

**Comment by LeCanard272** [comment]
Lidwien snapte het niet zo. gaan we nu over bespreken hoe we  dat gaan oppakken #140

**Comment by roel0064** [comment]
Dit issue is weer naar process gezet omdat er een aanpassing is gemaakt in de techniek van de DFD validatie. Lidwien zal een nieuwe mail krijgen.

**Comment by LeCanard272** [comment]
We hebben een deadline gesteld voor woensdag. Wanneer we dan nog niets gehoord hebben gaan we er vanuit dat ze akkoord gaan met de DFD

**Comment by KylianLauerHZICT** [comment]
![image](https://user-images.githubusercontent.com/36400283/100107148-a0d9bc80-2e69-11eb-9dc1-42dac99874f4.png)

**Comment by LeCanard272** [comment]
morgen even overleggen hoe hiermee verder te gaan

**Comment by LeCanard272** [comment]
We hebben Lidwien een persoonlijk bericht gestuurd. Hierin de vraag of ze nog feedback voor ons heeft of dat ze nog in gesprek wilt hierover. 2*10 min = +20 min = 2 uur totaal al wel ongeveer

**Comment by LeCanard272** [comment]
nog altijd geen reactie. nu 3* geprobeerd.

**Comment by LeCanard272** [comment]
vandaag ineens 3 mails gehad over dit onderwerp. maandag 11.00 gaan we deze bekijken en zien wat de bedoeling is.

**Comment by LeCanard272** [comment]
we hebben een plan gemaakt hoe we dit gaan aanpakken.
tim en niels hebben morgen overleg met lidwien ed. 

hierna kunnen we het dfd omzetten tot een leesbare versie voor hen. (adhv hun templates) 

het DFD moet uiteindelijk weer uitgestuurd worden ter validatie

**Comment by LeCanard272** [comment]
Veranderd naar high prio omdat het nu veranderd is naar sprint goal

**Comment by roel0064** [comment]
DFD is bijgewerkt aan de hand van feedback. We zullen het opnieuw moeten uitsturen ter validatie.
2 * 1 uur. mee bezig geweest.

**Comment by LeCanard272** [comment]
![image](https://user-images.githubusercontent.com/36400283/100889572-934eb300-34b7-11eb-8e11-71a57b8e2f21.png)
het DFD staat in Onedrive\HZ University of Applied Sciences\B.A.U. Consultants - General\DFD's\input ISM 3.1.png
We hebben het DFD weer ter validatie uitgestuurd naar Lidwien en Anne. De ticket is hierbij afgemaakt, maar we laten hem na de QA weer op de backlog staan tot we antwoord hebben. 

in totaal zijn we nu 6,5 uur hiermee bezig geweest.
