### ISSUE TITLE
Stakeholdermap valideren en bijwerken

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#60]

**Comment by GoldMercy** [comment]
valideren bij opdrachtgever

**Comment by LeCanard272** [comment]
in de stakeholder matrix de opdrachtgever toevoegen.

**Comment by LeCanard272** [comment]
klaar. opdrachtgever is toegevoegd op de juiste plekken.
2*5 min is 10 min mee bezig geweest.

**Comment by LeCanard272** [comment]
te vinden in teams> BAU> business understanding > stakeholdermap
