### ISSUE TITLE
KPI-Programma connectie visualiseren 

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#63]
Creeër een visualisatie(sketch oid) van de KPI's en hoe deze verbonden zijn met de programma's.
Denk hierbij aan het overleg die we met Greg gehad hebben woensdag.

**Comment by LeCanard272** [comment]
Mapping visualisatie is gemaakt met draw io.
Per programma is een branch gemaakt waarin de KPI's aan gekoppeld zijn.
Er is een kleursysteem gebruikt waardoor het eenvoudig is om de programma's en KPI's te onderscheiden.
Please review 24/09/2020

**Comment by LeCanard272** [comment]
toevoegen van algemene KPI's obv de jaarbegroting. 
Overleggen met Tim

**Comment by roel0064** [comment]
Overkoepelende thema's toegevoegd.
~30 min.
