### ISSUE TITLE
BPMN en DFD interviews regelen (Ivan de Bree)

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#65]

**Comment by LeCanard272** [comment]
Mail is opgesteld, moet nog opgestuurd worden naar betreffende persoon.

**Comment by HasinaNoori** [comment]
Nieuwe mail opgesteld en 7 RC (Ivan de Bree, Jo Nieuwlands, Mirjam Zegers, Esther Jager, Michiel Pouwer, Marty den Dekker & Lidwien Willemse) gemaild.

**Comment by roel0064** [comment]
User storie is gesplit per resultaatcoordinator

**Comment by HasinaNoori** [comment]
Interview is ingepland op donderdag 1 oktober tussen 13.00 - 15.00 met Rik & Niels.

**Comment by HasinaNoori** [comment]
In totaal 2 uur mee bezig geweest.
