### ISSUE TITLE
De opdrachtgever benaderen

### ISSUE THREAD

**Issue by kcpveen** [GoldMercy/B.A.U.-Consultants#73]
De opdrachtgever benaderen omtrent het verkrijgen van de datasets. Dit omdat dit van hoog belang is voor de vooruitgang van het project en zeker voor het maken van het dashboard.

**Comment by GoldMercy** [comment]
Opdrachtgever benaderd. Resultaat: RC's hebben niet de datasets die we verwacht hadden

**Comment by roel0064** [comment]
30 min
