### ISSUE TITLE
document verantwoordelijkheden Lead developer opstellen

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#74]
Schrijf een document waarin besproken wordt wat er overlegd is met pascal, en wat de rolbeschrijving van de Lead Developer is.

**Comment by Nienkedn** [comment]
In teams hebben we in het document rolverdeling-beschrijving de taken van de lead developer met onze eigen invulling aangepast. Hierbij is de feedback van Pascal meegenomen.

**Comment by HasinaNoori** [comment]
De Lead Developer taken voor mezelf doorgenomen en mijn verwachtingen van het team via teams gecommuniceerd. Taken zijn in het bestand Rolverdeling-beschrijving (Map Agile -> Groepsafspraken) te vinden.  In totaal 2 uur mee bezig geweest.
