### ISSUE TITLE
Meeting met claudia

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#76]
Meeting met claudia over proceseigenaren.
10:00 29-9-2020

**Comment by Nienkedn** [comment]
We hebben een teams meeting gehad met het hele team + Claudia + Anne. In deze meeting is het duidelijk geworden wat Claudia voor werk doet, wat haar functie inhoud en hoe haar functie past in het bedrijf.

**Comment by roel0064** [comment]
7 uur totaal
