### ISSUE TITLE
Interviewvragen opstellen

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#78]
Extra interviewvragen opstellen voor de RC's. De vragen zijn gefocust op hoe de data verzameld wordt door de RC's, wat zij er mee doen, hoe ze opgeslagen worden en wat er mee gebeurt.

**Comment by GoldMercy** [comment]
Moet nog meegenomen worden in de tracker berekening

**Comment by GoldMercy** [comment]
Interviewvragen Resultaatcoördinatoren aangevuld met extra vragen

**Comment by roel0064** [comment]
45min
