### ISSUE TITLE
Interview met Michiel

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#79]
Interview afnemen met Michiel in de functie Projectrealisatie.
Tijd: 6 oktober van 15:00 - 17:00
Deze interview kan het beste afgenomen worden door dezelfde mensen die Marty interviewen aangezien die dezelfde functie dekken.

**Comment by roel0064** [comment]
Interview duurde 45min. Michiel heeft ons nog een aantal risk gerelateerde documenten beloofd die ons verder kunnen helpen bij het begrijpen van de KPIs. Er is al een mail gestuurd om deze documenten op te vragen.
Het interview is opgenomen en moet nog uitgewerkt worden.
