### ISSUE TITLE
Interview met Marty

### ISSUE THREAD

**Issue by GoldMercy** [GoldMercy/B.A.U.-Consultants#80]
Interview afnemen met Marty in de functie Projectrealisatie.
Tijd: 6 oktober van 11:00 - 12:00 via de Teams van Waterschap.
Deze interview kan het beste afgenomen worden door dezelfde mensen die Michiel interviewen aangezien die dezelfde functie dekken.

**Comment by roel0064** [comment]
Interview is gedaan. ~30min. Moet nog uitgewerkt worden.
