### ISSUE TITLE
Interview met Ivan

### ISSUE THREAD

**Issue by kcpveen** [GoldMercy/B.A.U.-Consultants#81]
Een interview afleggen met Ivan van beleid formulering en strategie vorming.
Voor dit interview staat er een afspraak op Donderdag 1 oktober van 13.00u tot 15.00u via de teams van waterschap.

**Comment by szra0003** [comment]
Interview gehouden en genotuleerd. Dit is uitgewerkt in "Interview Ivan de Bree.docx". Deze is te vinden in de folder interview waterschap op teams ~ tijd besteed = 3 uur
