### ISSUE TITLE
Mock-up Dashboard

### ISSUE THREAD

**Issue by kcpveen** [GoldMercy/B.A.U.-Consultants#82]
Er moet een mockup gemaakt worden van de integrale sturingsmonitor om ons beeld van de sturingsmonitor in het dashboard te visualiseren. Dit kunnen wij gebruiken om zo snel mogelijk te testen als dit beeld acceptabel en op lijn is met wat de opdrachtgever wilt.

**Comment by kcpveen** [comment]
Rik en ik pakken deze op.
Dit valt onder de 20% marge van de sprint uren. @KylianLauerHZICT

**Comment by LeCanard272** [comment]
ok. prima

**Comment by GoldMercy** [comment]
3,5 uur aan bezig geweest so far...
Main page van het dashboard + begin van waterkeringen page gevisualiseerd.

**Comment by kcpveen** [comment]
Nog 1.5 uur aan bezig geweest. Dit maakt het tot nu toe 5 uur in totaal. We hadden hier een XL (8u) voor ingepland en wordt nu veranderd naar een  L (6u).

Waterkeringen page is volledig gevisualiseerd + de mockup is interactief gemaakt en is daarbij na review ready voor de eerste user tests.

De link naar de mockup/visualisatie: https://app.moqups.com/2VMpnviraG/view/page/aa9df7b72
