### ISSUE TITLE
Exploring Inventarisatie Activiteiten dataset

### ISSUE THREAD

**Issue by kcpveen** [GoldMercy/B.A.U.-Consultants#9]

**Comment by LeCanard272** [comment]
eerst duidelijk krijgen wat er onder exploring data valt.
later kan opnieuw t shirt sizing toegepast worden

**Comment by Nienkedn** [comment]
Users explore a large data set in an unstructured way to uncover initial patterns, characteristics, and points of interest. This process isn’t meant to reveal every bit of information a dataset holds, but rather to help create a broad picture of important trends and major points to study in greater detail.
