### ISSUE TITLE
Interview Mirjam afnemen

### ISSUE THREAD

**Issue by Nienkedn** [GoldMercy/B.A.U.-Consultants#90]

**Comment by LeCanard272** [comment]
er wordt nog een laatste bericht naar mirjam gestuurd voor het afnemen van deze interview. 
wordt hier ook niet op gereageerd, kunnen we bespreken of we hiermee het laten gaan.

**Comment by LeCanard272** [comment]
we hebben besloten dit even in de ijskast te zetten, tot we hier mee verder gaan, of dat mirjam reageert, of er een andere ontwikkeling hiervoor bedacht wordt.  High prio weg.

**Comment by HasinaNoori** [comment]
Idem #92
