### ISSUE TITLE
Interview Jo afnemen

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#91]
Houd het interview met Jo over data aanleveren aan naar de stuurhut

**Comment by HasinaNoori** [comment]
Interview ingepland op donderdag 15 oktober tussen 10.00 en 12.00 via teams. Interview zal worden afgenomen door Rik & Tim.

**Comment by roel0064** [comment]
Interview duurde 30 min * 2 (personen)

Gaat verder in issue #93
