### ISSUE TITLE
Interview Mirjam verwerken

### ISSUE THREAD

**Issue by Nienkedn** [GoldMercy/B.A.U.-Consultants#92]

**Comment by LeCanard272** [comment]
wat: (als) het interview van mirjam geweest is , verwerken in de projectdocumentatie

**Comment by LeCanard272** [comment]
idem comment 1-12 #90 high prio weg

**Comment by HasinaNoori** [comment]
Issue zal niet worden opgepakt omdat deze niet relevant is. Bij de stand-down kan besproken worden of de ticket gesloten mag worden.
