### ISSUE TITLE
interview Jo verwerken

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#93]
Verwerk de uitkomsten van het interview met Jo.

**Comment by roel0064** [comment]
Uitwerking wordt gesplitst. Ik doe de eerste helft & Rik de tweede.

**Comment by roel0064** [comment]
1e gedeelte (18min recording) is uitgewerkt. Dit koste mij bijna 2 uur.
Zie "General/Interviews waterschapInterviews waterschap/Afgenomen interviews/Interview van Jo Nieuwlands.docx" voor de uitwerking. De tekst is geen direct transcript geworden. Deze is geparafraseerd en verdeeld onder logishe hoofdstukken.

**Comment by GoldMercy** [comment]
Side B van het interview is ook uitgewerkt, koste me 2,5 uur. Zal bijgevoegd worden aan het document van Tim. Ongeveer hetzelfde uitgewerkt. Veelal letterlijk overgenomen wat er gezegd is, alleen de dingen die belangrijk zijn zijn overgenomen.
