### ISSUE TITLE
Interview met Esther afnemen

### ISSUE THREAD

**Issue by szra0003** [GoldMercy/B.A.U.-Consultants#94]
Houd het interview met Esther over data aanleveren aan naar de stuurhut

**Comment by LeCanard272** [comment]
Terug naar backlog omdat Esther niet aanwezig is. Sprint 4 opnieuw oppakken.

**Comment by HasinaNoori** [comment]
Interview is op dinsdag 17 november tussen 08.00 - 09.00 ingepland met Niels & Rik.  Uitnodiging is verstuurd.
