### ISSUE TITLE
Interview Esther uitwerken

### ISSUE THREAD

**Issue by szra0003** [GoldMercy/B.A.U.-Consultants#95]
Het opgenomen interview van Esther moet uitgewerkt worden zodat deze geanalyseerd kan worden.

**Comment by LeCanard272** [comment]
Terug naar backlog omdat Esther niet aanwezig is. Sprint 4 opnieuw oppakken.

**Comment by LeCanard272** [comment]
was een duplicate ticket voor gemaakt. #137 - is ook al opgelost.
ticket direct naar closed
