### ISSUE TITLE
Interview Lidwien uitwerken

### ISSUE THREAD

**Issue by szra0003** [GoldMercy/B.A.U.-Consultants#97]
Het opgenomen interview van Lidwien moet uitgewerkt worden zodat deze geanalyseerd kan worden.

**Comment by GoldMercy** [comment]
1 uur al bezig geweest op 2 november

**Comment by GoldMercy** [comment]
Interview van Lidwien is uitgewerkt en te vinden onder General > Interviews waterschap, totaal 3 uur bezig geweest
