### ISSUE TITLE
Functioneel testen Dashboard plannen

### ISSUE THREAD

**Issue by LeCanard272** [GoldMercy/B.A.U.-Consultants#98]
Plan de functionele tests voor het Dashboard met de personen die we hierbij willen betrekken.

**Comment by LeCanard272** [comment]
plan wat je wilt testen en met wie, en neem contact met ze op voor een afspraak

**Comment by HasinaNoori** [comment]
Testen zijn met de betreffende personen  (RC's behalve Miriam & Anne) gedeeld d.m.v. mail. In totaal 1 uur mee bezig geweest.
