### ISSUE TITLE
Technisch onderzoek naar mogelijkheden Tableau

### ISSUE THREAD

**Issue by Nienkedn** [GoldMercy/B.A.U.-Consultants#99]
Onderzoeken of het mogelijk is om de mock up die we hebben gemaakt te realiseren is in Tableau. Dit onderzoek moet vastgelegd worden in tekst.

**Comment by kcpveen** [comment]
Ik pak deze nu ook op

**Comment by HasinaNoori** [comment]
Aan de hand van het onderzoek besloten dat er data nodig is om het onderzoek verder voort te zetten in Tableau. Hiervoor zal onderzoek worden gedaan naar de aanleveringsdata #113 en zal een dummy dataset worden opgezet #114 . Tot nu toe ongeveer 6 uur mee bezig geweest.
